### ISSUE TITLE
[Q] table of calibration values for well-known devices

### ISSUE THREAD

**Issue by eadmaster** [Arpapiemonte/openoise-meter#13]
add a table in the wiki with calibration values for well-known devices (e.g. iPhone models, Samsung Galaxy etc).

**Comment by no-identd** [comment]
Subsequent idea:
Integrate into the app directly. Note: these values would only be partially useful due to intRAmodel, intERdevice variations, including things like the impact of covers, but proper measurements could serve as a starting point to save time on fine-calibration using a professional meter. Not much time, but SURELY this time saving/loss adds up over time.

Which also brings up:
Ideally, calibration should use a full profile of the microphone response curve, akin to what https://www.lindentree.eu/sounds.php [No affiliation] does. For which I'll raise a separate issue, as well as for selecting the different microphones of the device.

**Comment by Arpapiemonte** [comment]
Hi,
thank you for the issue.
We are working to create a database with all the users's calibration.
In a future release, every user will be able to send us the own calibration, and we will publish the results after an analysis.
At the moment, we are only pretty sure about the iOS calibration (+24 dB).
We hope this can help.

**Comment by GhostDog98** [comment]
Hi, I saw this was closed as completed, how do I access this feature? I am unable to see any options in the app to use such a table for calibration...
